config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('rosetta/', include('rosetta.urls')),
    path('home/', include('home.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home_page_view, name = 'home'),
]

home/models.py
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext as _



class Portfolio(models.Model):
    name_customer = models.CharField(_("customer name"), max_length=255, blank=True)
    image = models.ImageField(verbose_name=_('image'), upload_to='cover/')
    date_time_created = models.DateTimeField(_("date created"), default=timezone.now)

    class Meta:
        verbose_name = _('portfolio')
        verbose_name_plural = _('portfolio')


class Customer_call(models.Model):
    full_name = models.CharField(_("full name"), max_length=100)
    phone_number = models.CharField(_("phone number"), max_length=11)
    message = models.TextField(_("message"))
    date_time_send_message = models.DateTimeField(_("date send message"),  auto_now_add=True)
    
    class Meta:
        verbose_name = _('message from user')
        verbose_name_plural = _('message from user')

    def __str__(self):
        return self.full_name

home/forms.py
from django import forms

from .models import Customer_call


class UserMessageForm(forms.ModelForm):
    class Meta:
        model = Customer_call
        fields = ['full_name','phone_number','message',]
        

home/views.py
from django.shortcuts import render
from django.views.generic import ListView, TemplateView

from .models import Portfolio
from .forms import UserMessageForm

# class HomePage(ListView):
#     model = Portfolio
#     template_name = 'home/home.html'
#     context_object_name = 'portfolio'
    
# def message_from_user(request):
#     if request.method =='POST':
#         user_message = UserMessageForm(request.POST)
#         if user_message.is_valid():
#             user_message.save()
#             user_message = UserMessageForm()
#         else:
#             user_message = UserMessageForm()
#         return render(request, 'home/home.html',{'form':user_message})

def home_page_view(request):
    portfolio = Portfolio.objects.all()
    if request.method =='POST':
        form = UserMessageForm(request.POST)
        if form.is_valid():
            form.save()
            form = UserMessageForm()
    else:
        form = UserMessageForm()
    return render(request, 'home/home.html', {'form':form, 'portfolio':portfolio})
    

home/templates/home/home.html
{% extends "_base.html" %}
{% load crispy_forms_tags %}
{% load i18n %}
{% load static %}

{% block page_title %}
    {% trans "home page" %}
{% endblock page_title %}


{% block content %}
    <!-- Mobile Header -->
    <div class="mobile-header mobile-visible">
        <div class="mobile-logo-container">
            <div class="mobile-site-title"> {% trans "sepide mahzon" %}</div>
        </div>

        <a class="menu-toggle mobile-visible">
            <i class="fa fa-bars"></i>
        </a>
    </div>
    <!-- /Mobile Header -->
     

    <!-- Main Content -->
    <div id="main" class="site-main">
        <!-- Page changer wrapper -->
        <div class="pt-wrapper">
            <!-- Subpages -->
            <div class="subpages">

    <!-- Home Subpage -->
    <section class="pt-page" data-id="home">
        <div class="section-inner start-page-content">
            <div class="page-header">
                <div class="row">
                    <div class="col-sm-4 col-md-4 col-lg-4">
                        <div class="photo">
                            <img src="{% static "images/photo1.png" %}" alt="">
                        </div>
                    </div>

                    <div class="col-sm-8 col-md-8 col-lg-8">
                        <div class="title-block">
                            <h1> {% trans "sepide mahzon" %}</h1>
                            <div class="owl-carousel text-rotation">                                    
                                <div class="item">
                                    <div class="sp-subtitle">{% trans "hair transplant" %}</div>
                                </div>
                                <div class="item">
                                    <div class="sp-subtitle">{% trans "stop hair loss" %}</div>
                                </div>
                            </div>
                        </div>

                        <div class="social-links">
                            <a href="#"><i class="fa fa-telegram"></i></a>
                            <a href="#"><i class="fa fa-instagram"></i></a>
                            <a href="#"><i class="fa fa-facebook"></i></a>
                            <a href="#"><i class="fa fa-twitter"></i></a>
                        </div>
                    </div>
                </div>
            </div>

            <div class="page-content">
                <div class="row">

                    <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
                        <div class="about-me">
                            <div class="block-title">
                                <h3>{% trans "about " %} <span>{% trans "me" %}</span></h3>
                            </div>
                            <p>{% trans "description about me" %}</p>
                        </div>
                    </div>

                    <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
                        <ul class="info-list">
                            <li><span class="title">{% trans "birth date" %}</span> <span class="value">1366</span></li>
                            <li><span class="title">{% trans "email" %}</span> <span class="value ltr_text"><a href="mailto:email@example.com">Sepidehmahzoon1@gmail.com</a></span></li>
                            <li><span class="title">{% trans "phone number whats app" %}</span> <span class="value ltr_text">090543724225</span></li>
                        </ul>
                    </div>

                </div>
            </div>
        </div>
    </section>
    <!-- End of Home Subpage -->
    <!-- Portfolio Subpage -->
        <section class="pt-page" data-id="portfolio">
        <div class="section-inner custom-page-content">
            <div class="page-header color-1">
                <h2>{% trans "portfolio" %}</h2>
            </div>
            <div class="page-content">

                <!-- Portfolio Content -->
                <div class="portfolio-content">

                    <!-- Portfolio filter -->
                    <ul id="portfolio_filters" class="portfolio-filters">
                        <li>
                            <a class="filter btn btn-sm btn-link" data-group="illustration">{% trans "image" %}</a>
                        </li>
                      
                    </ul>
                    <!-- End of Portfolio filter -->

                    <!-- Portfolio Grid -->
                    <div id="portfolio_grid" class="portfolio-grid portfolio-masonry masonry-grid-3">

                        <!-- Portfolio Item 3 -->
                         {% for item in portfolio %}
                            <figure class="item" data-groups='["all","illustration"]'>
                                <a href="{{item.image.url}}" class="lightbox" title="{% trans "image name" %}">
                                    <img src="{{item.image.url}}" alt="">
                                    <div>
                                        <h5 class="name">{{item.name_customer}}</h5>
                                        <small>{% trans "image" %}</small>
                                        <i class="fa fa-image"></i>
                                    </div>
                                </a>
                            </figure>
                            <!-- /Portfolio Item 3 -->
                         {% endfor %}
                    </div>
                    <!-- /Portfolio Grid -->

                </div>
                <!-- /Portfolio Content -->
            </div>
        </div>
    </section>
    <!-- /Portfolio Subpage -->
    <!-- Contact Subpage -->
        <section class="pt-page" data-id="contact">
        <div class="section-inner custom-page-content">
            <div class="page-header color-1">
                <h2>{% trans "call" %}</h2>
            </div>
            <div class="page-content">

                <div class="row">


                    <div class="col-sm-6 col-md-6">
                        <div class="block-title">
                            <h3><span>{% trans "call" %}</span> {% trans "with me" %}</h3>
                        </div>
                        <form method="POST" action="{% url "home:home" %}">
                            {% csrf_token %}
                            <div class="messages"></div>

                            <div class="controls">
                                <div class="form-group form-group-with-icon">
                                    <i class="fa fa-user"></i>
                                    <label>{% trans "full name" %}</label>
                                    <input id="form_name" type="text" name="full_name" class="form-control" placeholder required="required" data-error={% trans "enter full name is required" %}>
                                    <div class="form-control-border"></div>
                                    <div class="help-block with-errors"></div>
                                </div>

                                <div class="form-group form-group-with-icon">
                                    <i class="fa fa-phone"></i>
                                    <label>{% trans "phone number" %}</label>
                                    <input id="form_phone_number" type="text" name="phone_number" class="form-control"max='11' placeholder required="required" dir="ltr" data-error={% trans "enter phone number is required" %}>
                                    <div class="form-control-border"></div>
                                    <div class="help-block with-errors"></div>
                                </div>

                                <div class="form-group form-group-with-icon">
                                    <i class="fa fa-comment"></i>
                                    <label>{% trans "your message for me" %}  ...</label>
                                    <textarea id="form_message" name="message" class="form-control" placeholder rows="3" required="required" data-error={% trans "enter your message" %}></textarea>
                                    <div class="form-control-border"></div>
                                    <div class="help-block with-errors"></div>
                                </div>

                                <!-- <div class="g-recaptcha" data-sitekey="6LdqmCAUAAAAAMMNEZvn6g4W5e0or2sZmAVpxVqI"></div> -->

                                <button type="submit">{% trans "send message" %}</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- End Contact Subpage -->

{% endblock content %}

templates/_base.html
{% load static %}

{% load i18n %}
<!DOCTYPE html>
<html lang="fa" class="no-js">
	<head>
		<meta charset="UTF-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge"> 
		<title>{% block page_title %}{% endblock page_title %}</title>
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
		
		<link rel="shortcut icon" href="{% static "images/favicon.png" %}">

		<link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}" type="text/css">
		<link rel="stylesheet" href="{% static "css/normalize.css" %}" type="text/css">
		<link rel="stylesheet" href="{% static "css/animate.css" %}" type="text/css">
		<link rel="stylesheet" href="{% static "css/transition-animations.css" %}" type="text/css">
		<link rel="stylesheet" href="{% static "css/owl.carousel.css" %}" type="text/css">
		<link rel="stylesheet" href="{% static "css/magnific-popup.css" %}" type="text/css">
		<link rel="stylesheet" href="{% static "css/main-blue.css" %}" type="text/css">

		<!-- This styles needs for demo -->
		<link rel="stylesheet" href="{% static "preview/lmpixels-demo-panel.css" %}" type="text/css">
		<!-- /This styles needs for demo -->

		<script src="{% static "js/jquery-2.1.3.min.js" %}"></script>
		<script src="{% static "js/modernizr.custom.js" %}"></script>
		<!-- <script src="https://www.google.com/recaptcha/api.js"></script> -->
	</head>

	<body class="material-template">
		<!-- Loading animation -->
		<div class="preloader">
			<div class="preloader-animation">
				<div class="preloader-spinner">
				</div>
			</div>
		</div>
		<!-- /Loading animation -->

		<div id="page" class="page">
			<!-- Header -->
			<header id="site_header" class="header mobile-menu-hide">
				<div class="header-content">
					<div class="site-title-block mobile-hidden">
						<div class="site-title">{% trans "sepide" %} <span>{% trans "mahzon" %}</span></div>
					</div>

					<!-- Navigation -->
					<div class="site-nav">
						<!-- Main menu -->
						<ul id="nav" class="site-main-menu">
							<li>
								<a class="pt-trigger" href="#home">{% trans "home" %}</a><!-- href value = data-id without # of .pt-page. -->
							</li>
							<li>
								<a class="pt-trigger" href="#portfolio">{% trans "portfolio" %}</a>
							</li>
							<li>
								<a class="pt-trigger" href="#contact">{% trans "call" %}</a>
							</li>
						</ul>
						<!-- /Main menu -->
					</div>
					<!-- Navigation -->
				</div>
			</header>
			<!-- /Header -->

        {% block content %}
        {% endblock content %}
		</div>

		<script type="text/javascript" src="{% static "js/bootstrap.min.js" %}"></script>
		<script type="text/javascript" src="{% static "js/pages-switcher.js" %}"></script>
		<script type="text/javascript" src="{% static "js/validator.js" %}"></script>
		<script type="text/javascript" src="{% static "js/jquery.shuffle.min.js" %}"></script>
		<script type="text/javascript" src="{% static "js/masonry.pkgd.min.js" %}"></script>
		<script type="text/javascript" src="{% static "js/owl.carousel.min.js" %}"></script>
		<script type="text/javascript" src="{% static "js/jquery.magnific-popup.min.js" %}"></script>
		<script type="text/javascript" src="{% static "js/jquery.hoverdir.js" %}"></script>
		<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAEn4c_T1rFt7ltf_oNavnjND8dDPm4KQs&language=fa"></script>
		<script type="text/javascript" src="{% static "js/jquery.googlemap.js" %}"></script>
		<script type="text/javascript" src="{% static "js/main.js" %}"></script>

		<!-- Demo Color changer Script -->
		<script src="{% static "preview/lmpixels-demo-panel.js" %}"></script>
		<!-- /Demo Color changer Script -->
	</body>
</html>